INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, NULL, 'لباس و پوشاک', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, NULL, 'آرایشی بهداشتی', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, NULL, 'لوازم جانبی موبایل', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (4, NULL, 'گوشی موبایل', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (5, NULL, 'خودرو', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (6, NULL, 'پیراهن', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (7, NULL, 'شلوار', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (8, NULL, 'روسری', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (9, NULL, 'جوراب', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (10, NULL, 'کرم مرطوب کننده', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (11, NULL, 'خمیردندان', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (12, NULL, 'دهانشویه', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (13, NULL, 'لوازم برقی', NULL, NULL, NULL);
INSERT INTO `categories` (`category_id`, `category_ref_id`, `title`, `created_at`, `updated_at`, `deleted_at`) VALUES (14, NULL, 'جاروبررقی', NULL, NULL, NULL);
INSERT INTO `product_prices` (`product_price_id`, `product_ref_id`, `price`, `shop_ref_id`) VALUES (1, 5, 50.00, NULL);
INSERT INTO `product_prices` (`product_price_id`, `product_ref_id`, `price`, `shop_ref_id`) VALUES (2, 6, 60.00, NULL);
INSERT INTO `products` (`product_id`, `title`, `description`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 'p1', NULL, NULL, NULL, NULL);
INSERT INTO `products` (`product_id`, `title`, `description`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, 'p1', NULL, NULL, NULL, NULL);
INSERT INTO `products` (`product_id`, `title`, `description`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 'اسم موبایل', NULL, NULL, NULL, NULL);
INSERT INTO `products` (`product_id`, `title`, `description`, `created_at`, `updated_at`, `deleted_at`) VALUES (4, 'اسم جاروبرقی', NULL, NULL, NULL, NULL);
INSERT INTO `products` (`product_id`, `title`, `description`, `created_at`, `updated_at`, `deleted_at`) VALUES (5, 'گلکسی', NULL, NULL, NULL, NULL);
INSERT INTO `products` (`product_id`, `title`, `description`, `created_at`, `updated_at`, `deleted_at`) VALUES (6, 'p2', NULL, NULL, NULL, NULL);
INSERT INTO `shops` (`shop_id`, `owner_id`, `titlt`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, NULL, 'A', NULL, NULL, NULL);

